blank_issues_enabled: false
contact_links:
  - name: Bug
    url: https://github.com/alexcnichols/test-issue-template-config/issues/new?assignees=&labels=bug&template=feature_request.md&title=
    about: Please ask and answer questions here.
